// Glossary data tables — English and Spanish. Both share the same `slug`
// for every term so:
//   1. data-glossary="<slug>" markers from the auto-linker map to the same
//      term in both locales (clean mention-index across both languages),
//   2. hreflang reciprocal links between /glossary/<slug>/ and
//      /es/glossary/<slug>/ are trivial to emit,
//   3. adding more locales later only requires another entry in the LOCALES
//      object — no schema changes.
//
// `aliases` are matched case-insensitively by the auto-linker for surface
// forms beyond the canonical term (e.g. "WVTR" vs. "water vapor
// transmission rate"). For Spanish, aliases include common English terms
// readers may encounter inline since most industry literature is in English.

export const GLOSSARY_EN = [
  // Process & science
  { term: "Water activity (aw)", slug: "water-activity", category: "Process & science",
    aliases: ["water activity"],
    definition: "A measure of how *available* the water in a food is, reported on a 0–1 scale. Pure water sits near 1.0; freeze-dried fruit typically sits well below 0.3. Water activity predicts microbial and texture stability better than moisture content alone." },
  { term: "Moisture content", slug: "moisture-content", category: "Process & science",
    definition: "The percentage of a product's weight that is water. Premium freeze-dried fruit usually targets 1–4% residual moisture. A low moisture number does not guarantee crunch — water activity matters too." },
  { term: "Sublimation", slug: "sublimation", category: "Process & science",
    definition: "The phase transition from solid directly to vapor without passing through liquid. Freeze-drying removes water from frozen fruit by sublimation under low pressure, preserving the cellular structure." },
  { term: "Lyophilization", slug: "lyophilization", category: "Process & science",
    aliases: ["lyophilisation"],
    definition: "The technical name for freeze-drying. Frozen material is placed under vacuum so that water sublimates from the solid phase, leaving a porous dry structure." },
  { term: "Primary drying", slug: "primary-drying", category: "Process & science",
    definition: "The first and longest phase of a freeze-drying cycle. Bulk ice is removed by sublimation under controlled vacuum and shelf temperature. Most cycle time is spent here." },
  { term: "Secondary drying", slug: "secondary-drying", category: "Process & science",
    definition: "The final phase of a freeze-drying cycle. Bound water — the moisture still held inside the cell structure — is removed at higher shelf temperatures to reach the residual moisture target." },
  { term: "Eutectic point", slug: "eutectic-point", category: "Process & science",
    definition: "The temperature below which a solution is fully solid. For freeze-drying fruit, the product must stay below its eutectic or collapse temperature during primary drying or it will lose structure." },
  { term: "Cycle endpoint", slug: "cycle-endpoint", category: "Process & science",
    definition: "The point at which secondary drying is complete and the product has reached its target moisture and water activity. Pulling the cycle too early leaves residual moisture; running too long wastes energy and can over-dry the fruit." },

  // Raw material & format
  { term: "IQF (Individually Quick-Frozen)", slug: "iqf", category: "Raw material & format",
    aliases: ["IQF", "individually quick-frozen", "individually quick frozen"],
    definition: "Fruit frozen piece by piece at low temperature before processing. IQF lets producers run year-round and standardize specs, but ice crystal formation can rupture cell walls — sometimes visible in whole-piece formats." },
  { term: "Pre-treatment", slug: "pre-treatment", category: "Raw material & format",
    aliases: ["pretreatment", "pre-treatments"],
    definition: "Any step applied to fruit between intake and freezing — washing, cutting, dipping, blanching, or acidifying. Pre-treatment can prevent enzymatic browning and stabilize color for sensitive fruits like apple, banana, and pear." },
  { term: "Brix", slug: "brix", category: "Raw material & format",
    definition: "A measurement of dissolved solids — mostly sugars — in fruit juice, expressed in degrees. Higher Brix often correlates with stronger flavor in the finished freeze-dried product, though acidity and aroma compounds matter too." },
  { term: "Whole piece", slug: "whole-piece", category: "Raw material & format",
    aliases: ["whole pieces", "whole-piece"],
    definition: "Freeze-dried fruit sold as intact pieces — whole strawberries, whole blueberries, whole mango chunks. Whole-piece formats command premium pricing and demand tighter breakage control." },
  { term: "Crumble / fines", slug: "crumble-fines", category: "Raw material & format",
    aliases: ["fines"],
    definition: "Small fragments and powder produced when freeze-dried fruit breaks during processing, screening, or transport. Some breakage is normal; tolerance is defined by buyer spec." },
  { term: "Powder", slug: "powder", category: "Raw material & format",
    aliases: ["fruit powder", "freeze-dried powder"],
    definition: "Freeze-dried fruit milled into a fine powder. Used for color, flavor coverage, beverage applications, and ingredient systems. Same raw fruit can yield very different powder behavior depending on grind size and pre-screening." },

  // Quality & defects
  { term: "Enzymatic browning", slug: "enzymatic-browning", category: "Quality & defects",
    definition: "Surface darkening caused by enzymes reacting with oxygen after fruit is cut. Common in apple, banana, and pear. Can be controlled by pre-treatment and fast freezing." },
  { term: "Pigment fade", slug: "pigment-fade", category: "Quality & defects",
    definition: "Loss of color saturation in pigment-rich fruits — strawberry, raspberry, blueberry, cherry, dragon fruit. Often shows as washed-out, dusty, or grayish appearance rather than browning. Driven by oxygen exposure and weak packaging." },
  { term: "Breakage", slug: "breakage", category: "Quality & defects",
    definition: "The proportion of freeze-dried fruit that has broken from its intended piece size into fragments or powder. A controlled spec for premium products; transit damage can compound it." },
  { term: "Rehydration", slug: "rehydration", category: "Quality & defects",
    definition: "Unwanted moisture pickup after the product leaves the freeze dryer. Causes softening, clumping, and texture loss. The packaging system — film, seal, zipper, headspace, desiccant — is designed to prevent it." },

  // Packaging
  { term: "Barrier film", slug: "barrier-film", category: "Packaging",
    aliases: ["barrier films", "barrier-film"],
    definition: "The multilayer plastic structure used to make freeze-dried fruit pouches. Barrier performance is measured against water vapor and oxygen. Cannot be inferred from appearance — buyers should ask for the actual structure." },
  { term: "WVTR (Water Vapor Transmission Rate)", slug: "wvtr", category: "Packaging",
    aliases: ["WVTR", "water vapor transmission rate"],
    definition: "The rate at which water vapor passes through a barrier film under defined conditions, typically reported in g/m²/day. Lower WVTR means better humidity protection. The first packaging spec to check for freeze-dried fruit." },
  { term: "OTR (Oxygen Transmission Rate)", slug: "otr", category: "Packaging",
    aliases: ["OTR", "oxygen transmission rate"],
    definition: "The rate at which oxygen passes through a barrier film, typically reported in cc/m²/day. Lower OTR protects color, aroma, and oxidation-sensitive fruits. Second priority after WVTR for most freeze-dried fruit." },
  { term: "Metallized film", slug: "metallized-film", category: "Packaging",
    aliases: ["metallized films", "metallised film", "metallised films"],
    definition: "A flexible film with a thin vapor-deposited aluminum layer. Offers stronger humidity and oxygen protection than clear structures at lower cost than full foil. Common for mainstream freeze-dried fruit snack pouches." },
  { term: "Foil laminate", slug: "foil-laminate", category: "Packaging",
    aliases: ["foil laminates", "foil pouch", "foil pouches", "foil-based"],
    definition: "A flexible packaging structure built around an aluminum foil layer. Provides the strongest moisture and oxygen barrier in standard pouch formats. Used for export shipments, premium products, and humid distribution environments." },
  { term: "Desiccant", slug: "desiccant", category: "Packaging",
    aliases: ["desiccants"],
    definition: "A small packet — usually silica gel or molecular sieve — that absorbs moisture inside a sealed pouch. Helps protect freeze-dried fruit from humidity that enters during the package's service life. Not a substitute for proper film." },
  { term: "Oxygen absorber", slug: "oxygen-absorber", category: "Packaging",
    aliases: ["oxygen absorbers"],
    definition: "A packet that chemically removes residual oxygen from a sealed pouch. Protects color and aroma in oxidation-sensitive freeze-dried fruit. Different problem than a desiccant — they are not interchangeable." },
  { term: "Headspace", slug: "headspace", category: "Packaging",
    definition: "The empty volume inside a sealed pouch above the product. Excess headspace increases the residual oxygen load and the volume of humid air the desiccant must manage." },
  { term: "Heat seal", slug: "heat-seal", category: "Packaging",
    aliases: ["heat seals", "heat-seal"],
    definition: "The thermally bonded edge of a flexible pouch. A weak or inconsistent heat seal is a common failure point that defeats an otherwise good barrier film." },

  // Commercial
  { term: "MOQ (Minimum Order Quantity)", slug: "moq", category: "Commercial",
    aliases: ["MOQ", "MOQs", "minimum order quantity", "minimum order quantities"],
    definition: "The smallest quantity a supplier will accept on a single order, expressed in kilograms, cases, or units. MOQs reflect the supplier's batch size, packaging changeover cost, and willingness to run small lots." },
  { term: "Landed cost", slug: "landed-cost", category: "Commercial",
    aliases: ["landed costs"],
    definition: "The total cost of freeze-dried fruit delivered to the buyer's warehouse, including raw material, processing, packaging, freight, duties, brokerage, and handling. Often very different from the ex-works quote." },
  { term: "Dry yield", slug: "dry-yield", category: "Commercial",
    definition: "The amount of finished freeze-dried fruit produced from a unit of fresh or frozen input fruit. Varies by fruit, variety, ripeness, cut size, and format. A core input to landed cost calculations." },
  { term: "Usable yield", slug: "usable-yield", category: "Commercial",
    definition: "The portion of dry yield that meets the buying spec for a given application. A topping format may accept fragments that a premium whole-piece snack would reject. The number that actually matters for cost-in-use." },
  { term: "Private label", slug: "private-label", category: "Commercial",
    aliases: ["private-label"],
    definition: "An arrangement where a supplier produces freeze-dried fruit packaged under the buyer's brand, rather than the supplier's own. Common in retail, foodservice, and ingredient channels." },

  // Certifications
  { term: "SQF (Safe Quality Food)", slug: "sqf", category: "Certifications",
    aliases: ["SQF"],
    definition: "A GFSI-recognized food safety certification scheme used across freeze-dried fruit processing. Buyers often require SQF Level 2 or higher for branded retail supply." },
  { term: "BRCGS", slug: "brcgs", category: "Certifications",
    definition: "Brand Reputation Compliance Global Standards — a GFSI-recognized food safety certification widely used by European retailers and global ingredient buyers. Common at freeze-dried fruit suppliers serving export markets." },
  { term: "FSSC 22000", slug: "fssc-22000", category: "Certifications",
    definition: "A GFSI-recognized food safety management standard built on ISO 22000. Often required by multinational brands sourcing freeze-dried fruit ingredients at scale." },
  { term: "USDA Organic", slug: "usda-organic", category: "Certifications",
    definition: "A US Department of Agriculture certification for fruit grown and processed under defined organic standards. Affects raw material sourcing, processing aids, and label claim eligibility for freeze-dried fruit products sold in the US." },
];

export const GLOSSARY_ES = [
  // Proceso y ciencia
  { term: "Actividad de agua (aw)", slug: "water-activity", category: "Proceso y ciencia",
    aliases: ["actividad de agua", "water activity", "aw"],
    definition: "Una medida de qué tan *disponible* está el agua en un alimento, reportada en una escala de 0 a 1. El agua pura está cerca de 1.0; la fruta liofilizada típicamente está muy por debajo de 0.3. La actividad de agua predice la estabilidad microbiana y de textura mejor que el contenido de humedad por sí solo." },
  { term: "Contenido de humedad", slug: "moisture-content", category: "Proceso y ciencia",
    aliases: ["humedad residual", "moisture content"],
    definition: "El porcentaje del peso de un producto que es agua. La fruta liofilizada premium usualmente apunta a 1–4% de humedad residual. Un número bajo de humedad no garantiza crujiente — la actividad de agua también importa." },
  { term: "Sublimación", slug: "sublimation", category: "Proceso y ciencia",
    aliases: ["sublimation"],
    definition: "La transición de fase de sólido directamente a vapor sin pasar por líquido. La liofilización elimina el agua de la fruta congelada mediante sublimación a baja presión, preservando la estructura celular." },
  { term: "Liofilización", slug: "lyophilization", category: "Proceso y ciencia",
    aliases: ["lyophilization", "freeze-drying"],
    definition: "El nombre técnico de la congelación-deshidratación (freeze-drying). El material congelado se coloca al vacío para que el agua se sublime de la fase sólida, dejando una estructura porosa seca." },
  { term: "Secado primario", slug: "primary-drying", category: "Proceso y ciencia",
    aliases: ["primary drying"],
    definition: "La primera y más larga fase de un ciclo de liofilización. El hielo a granel se elimina por sublimación bajo vacío y temperatura de bandeja controlados. La mayor parte del tiempo de ciclo se gasta aquí." },
  { term: "Secado secundario", slug: "secondary-drying", category: "Proceso y ciencia",
    aliases: ["secondary drying"],
    definition: "La fase final de un ciclo de liofilización. El agua ligada — la humedad que aún se mantiene dentro de la estructura celular — se elimina a temperaturas de bandeja más altas para alcanzar el objetivo de humedad residual." },
  { term: "Punto eutéctico", slug: "eutectic-point", category: "Proceso y ciencia",
    aliases: ["eutectic point"],
    definition: "La temperatura por debajo de la cual una solución está completamente sólida. Para la liofilización de fruta, el producto debe permanecer por debajo de su punto eutéctico o de colapso durante el secado primario o perderá estructura." },
  { term: "Punto final del ciclo", slug: "cycle-endpoint", category: "Proceso y ciencia",
    aliases: ["cycle endpoint"],
    definition: "El punto en el cual el secado secundario está completo y el producto ha alcanzado su objetivo de humedad y actividad de agua. Detener el ciclo demasiado pronto deja humedad residual; correrlo demasiado tiempo desperdicia energía y puede sobre-secar la fruta." },

  // Materia prima y formato
  { term: "IQF (Congelación rápida individual)", slug: "iqf", category: "Materia prima y formato",
    aliases: ["IQF", "individually quick-frozen", "congelación rápida individual"],
    definition: "Fruta congelada pieza por pieza a baja temperatura antes del procesamiento. IQF permite a los productores correr todo el año y estandarizar las especificaciones, pero la formación de cristales de hielo puede romper las paredes celulares — a veces visible en formatos de pieza entera." },
  { term: "Pretratamiento", slug: "pre-treatment", category: "Materia prima y formato",
    aliases: ["pre-treatment", "pretreatment"],
    definition: "Cualquier paso aplicado a la fruta entre la entrada y la congelación — lavado, corte, inmersión, escaldado o acidificación. El pretratamiento puede prevenir el oscurecimiento enzimático y estabilizar el color para frutas sensibles como manzana, plátano y pera." },
  { term: "Brix", slug: "brix", category: "Materia prima y formato",
    aliases: ["Brix"],
    definition: "Una medida de sólidos disueltos — principalmente azúcares — en el jugo de fruta, expresada en grados. Un Brix más alto a menudo se correlaciona con un sabor más fuerte en el producto liofilizado terminado, aunque los compuestos de acidez y aroma también importan." },
  { term: "Pieza entera", slug: "whole-piece", category: "Materia prima y formato",
    aliases: ["whole piece", "whole pieces", "piezas enteras"],
    definition: "Fruta liofilizada vendida como piezas intactas — fresas enteras, arándanos enteros, trozos enteros de mango. Los formatos de pieza entera comandan precios premium y exigen un control más estricto de la rotura." },
  { term: "Migajas / finos", slug: "crumble-fines", category: "Materia prima y formato",
    aliases: ["crumble", "fines", "migajas", "finos"],
    definition: "Pequeños fragmentos y polvo producidos cuando la fruta liofilizada se rompe durante el procesamiento, el tamizado o el transporte. Algo de rotura es normal; la tolerancia se define por la especificación del comprador." },
  { term: "Polvo", slug: "powder", category: "Materia prima y formato",
    aliases: ["powder", "fruit powder", "polvo de fruta"],
    definition: "Fruta liofilizada molida en polvo fino. Se usa para color, cobertura de sabor, aplicaciones de bebidas y sistemas de ingredientes. La misma fruta cruda puede producir comportamientos de polvo muy diferentes dependiendo del tamaño de molienda y el pre-tamizado." },

  // Calidad y defectos
  { term: "Oscurecimiento enzimático", slug: "enzymatic-browning", category: "Calidad y defectos",
    aliases: ["enzymatic browning"],
    definition: "Oscurecimiento de la superficie causado por enzimas que reaccionan con el oxígeno después de cortar la fruta. Común en manzana, plátano y pera. Se puede controlar mediante pretratamiento y congelación rápida." },
  { term: "Pérdida de pigmento", slug: "pigment-fade", category: "Calidad y defectos",
    aliases: ["pigment fade", "pigment loss"],
    definition: "Pérdida de saturación de color en frutas ricas en pigmentos — fresa, frambuesa, arándano, cereza, fruta del dragón. A menudo se muestra como apariencia desvanecida, polvorienta o grisácea en lugar de oscurecimiento. Impulsada por la exposición al oxígeno y el empaque débil." },
  { term: "Rotura", slug: "breakage", category: "Calidad y defectos",
    aliases: ["breakage", "fragmentación"],
    definition: "La proporción de fruta liofilizada que se ha roto de su tamaño de pieza previsto en fragmentos o polvo. Una especificación controlada para productos premium; el daño en tránsito puede acumularla." },
  { term: "Rehidratación", slug: "rehydration", category: "Calidad y defectos",
    aliases: ["rehydration"],
    definition: "Absorción no deseada de humedad después de que el producto sale del liofilizador. Causa ablandamiento, aglutinamiento y pérdida de textura. El sistema de empaque — película, sello, cierre tipo zip, cabezal de aire, desecante — está diseñado para prevenirlo." },

  // Empaque
  { term: "Película barrera", slug: "barrier-film", category: "Empaque",
    aliases: ["barrier film", "barrier films", "películas barrera"],
    definition: "La estructura de plástico multicapa utilizada para fabricar bolsas de fruta liofilizada. El desempeño de la barrera se mide contra el vapor de agua y el oxígeno. No se puede inferir de la apariencia — los compradores deben pedir la estructura real." },
  { term: "WVTR (Tasa de transmisión de vapor de agua)", slug: "wvtr", category: "Empaque",
    aliases: ["WVTR", "water vapor transmission rate"],
    definition: "La tasa a la cual el vapor de agua pasa a través de una película barrera bajo condiciones definidas, típicamente reportada en g/m²/día. Un WVTR más bajo significa mejor protección contra la humedad. La primera especificación de empaque a verificar para la fruta liofilizada." },
  { term: "OTR (Tasa de transmisión de oxígeno)", slug: "otr", category: "Empaque",
    aliases: ["OTR", "oxygen transmission rate"],
    definition: "La tasa a la cual el oxígeno pasa a través de una película barrera, típicamente reportada en cc/m²/día. Un OTR más bajo protege el color, el aroma y las frutas sensibles a la oxidación. Segunda prioridad después del WVTR para la mayoría de la fruta liofilizada." },
  { term: "Película metalizada", slug: "metallized-film", category: "Empaque",
    aliases: ["metallized film", "metallised film"],
    definition: "Una película flexible con una delgada capa de aluminio depositada por vapor. Ofrece mayor protección contra la humedad y el oxígeno que las estructuras transparentes a menor costo que el foil completo. Común para bolsas de snack de fruta liofilizada de mercado masivo." },
  { term: "Laminado de aluminio (foil)", slug: "foil-laminate", category: "Empaque",
    aliases: ["foil laminate", "foil pouch", "laminado de foil", "bolsa de foil"],
    definition: "Una estructura de empaque flexible construida alrededor de una capa de papel aluminio. Proporciona la barrera más fuerte contra humedad y oxígeno en formatos de bolsa estándar. Se usa para envíos de exportación, productos premium y ambientes de distribución húmedos." },
  { term: "Desecante", slug: "desiccant", category: "Empaque",
    aliases: ["desiccant", "desecantes"],
    definition: "Un paquete pequeño — usualmente gel de sílice o tamiz molecular — que absorbe la humedad dentro de una bolsa sellada. Ayuda a proteger la fruta liofilizada de la humedad que entra durante la vida útil del paquete. No es sustituto de una película adecuada." },
  { term: "Absorbedor de oxígeno", slug: "oxygen-absorber", category: "Empaque",
    aliases: ["oxygen absorber", "absorbedores de oxígeno"],
    definition: "Un paquete que elimina químicamente el oxígeno residual de una bolsa sellada. Protege el color y el aroma en la fruta liofilizada sensible a la oxidación. Es un problema diferente que un desecante — no son intercambiables." },
  { term: "Cabezal de aire", slug: "headspace", category: "Empaque",
    aliases: ["headspace", "espacio de cabeza"],
    definition: "El volumen vacío dentro de una bolsa sellada por encima del producto. El cabezal de aire excesivo aumenta la carga de oxígeno residual y el volumen de aire húmedo que el desecante debe manejar." },
  { term: "Sello térmico", slug: "heat-seal", category: "Empaque",
    aliases: ["heat seal", "heat-seal"],
    definition: "El borde térmicamente unido de una bolsa flexible. Un sello térmico débil o inconsistente es un punto de falla común que derrota una película barrera por lo demás buena." },

  // Comercial
  { term: "MOQ (Cantidad mínima de pedido)", slug: "moq", category: "Comercial",
    aliases: ["MOQ", "minimum order quantity", "cantidad mínima"],
    definition: "La menor cantidad que un proveedor aceptará en un solo pedido, expresada en kilogramos, cajas o unidades. Los MOQ reflejan el tamaño de lote del proveedor, el costo de cambio de empaque y la disposición a correr lotes pequeños." },
  { term: "Costo entregado", slug: "landed-cost", category: "Comercial",
    aliases: ["landed cost", "costo de llegada"],
    definition: "El costo total de la fruta liofilizada entregada al almacén del comprador, incluyendo materia prima, procesamiento, empaque, flete, aranceles, corretaje y manejo. A menudo muy diferente de la cotización ex-works." },
  { term: "Rendimiento seco", slug: "dry-yield", category: "Comercial",
    aliases: ["dry yield"],
    definition: "La cantidad de fruta liofilizada terminada producida a partir de una unidad de fruta fresca o congelada de entrada. Varía según fruta, variedad, madurez, tamaño de corte y formato. Una entrada central a los cálculos de costo entregado." },
  { term: "Rendimiento utilizable", slug: "usable-yield", category: "Comercial",
    aliases: ["usable yield"],
    definition: "La porción del rendimiento seco que cumple con la especificación de compra para una aplicación dada. Un formato de cobertura puede aceptar fragmentos que un snack premium de pieza entera rechazaría. El número que realmente importa para el costo en uso." },
  { term: "Marca privada", slug: "private-label", category: "Comercial",
    aliases: ["private label", "private-label"],
    definition: "Un arreglo donde un proveedor produce fruta liofilizada empacada bajo la marca del comprador, en lugar de la propia del proveedor. Común en venta minorista, foodservice y canales de ingredientes." },

  // Certificaciones
  { term: "SQF (Calidad Alimentaria Segura)", slug: "sqf", category: "Certificaciones",
    aliases: ["SQF", "Safe Quality Food"],
    definition: "Un esquema de certificación de seguridad alimentaria reconocido por GFSI utilizado en el procesamiento de fruta liofilizada. Los compradores a menudo requieren SQF Nivel 2 o superior para el suministro minorista con marca." },
  { term: "BRCGS", slug: "brcgs", category: "Certificaciones",
    aliases: ["BRCGS", "BRC"],
    definition: "Brand Reputation Compliance Global Standards — una certificación de seguridad alimentaria reconocida por GFSI ampliamente utilizada por minoristas europeos y compradores globales de ingredientes. Común en proveedores de fruta liofilizada que sirven mercados de exportación." },
  { term: "FSSC 22000", slug: "fssc-22000", category: "Certificaciones",
    aliases: ["FSSC 22000"],
    definition: "Un estándar de gestión de seguridad alimentaria reconocido por GFSI construido sobre ISO 22000. A menudo requerido por marcas multinacionales que adquieren ingredientes de fruta liofilizada a escala." },
  { term: "USDA Orgánico", slug: "usda-organic", category: "Certificaciones",
    aliases: ["USDA Organic", "USDA Orgánico", "orgánico USDA"],
    definition: "Una certificación del Departamento de Agricultura de EE. UU. para fruta cultivada y procesada bajo estándares orgánicos definidos. Afecta el abastecimiento de materia prima, las ayudas de procesamiento y la elegibilidad para declaraciones de etiqueta para productos de fruta liofilizada vendidos en EE. UU." },
];

export const GLOSSARY_CATEGORY_ORDER_EN = [
  "Process & science",
  "Raw material & format",
  "Quality & defects",
  "Packaging",
  "Commercial",
  "Certifications",
];

export const GLOSSARY_CATEGORY_ORDER_ES = [
  "Proceso y ciencia",
  "Materia prima y formato",
  "Calidad y defectos",
  "Empaque",
  "Comercial",
  "Certificaciones",
];

// UI labels for the glossary surface, per locale. Keeps the renderer
// language-agnostic — only the chrome strings differ between the two.
export const GLOSSARY_LABELS = {
  en: {
    pageTitle: "Freeze-Dried Fruit Glossary",
    eyebrowPrefix: "Reference",
    termsSuffix: "terms",
    pageIntro: "Plain-language definitions of the technical, commercial, and packaging terms that come up across the freeze-dried fruit category — from water activity and sublimation to landed cost and barrier films. Each term has its own page with the full definition, related terms, and articles that use it.",
    breadcrumbHome: "Home",
    breadcrumbGlossary: "Glossary",
    readFullDefinition: "Read full definition",
    relatedTermsInPrefix: "Related terms in",
    mentionsHeading: "Articles that use this term",
    emptyMentions: "No articles currently link to this term. Try searching the",
    emptyMentionsLink: "archive",
    backToAll: "Back to all terms",
    glossaryEyebrow: "Glossary",
    contentsLabel: "Glossary contents",
  },
  es: {
    pageTitle: "Glosario de fruta liofilizada",
    eyebrowPrefix: "Referencia",
    termsSuffix: "términos",
    pageIntro: "Definiciones en lenguaje sencillo de los términos técnicos, comerciales y de empaque que aparecen en la categoría de fruta liofilizada — desde actividad de agua y sublimación hasta costo entregado y películas barrera. Cada término tiene su propia página con la definición completa, términos relacionados y artículos que lo usan.",
    breadcrumbHome: "Inicio",
    breadcrumbGlossary: "Glosario",
    readFullDefinition: "Leer definición completa",
    relatedTermsInPrefix: "Términos relacionados en",
    mentionsHeading: "Artículos que usan este término",
    emptyMentions: "Actualmente no hay artículos que enlacen a este término. Prueba buscando en el",
    emptyMentionsLink: "archivo",
    backToAll: "Volver a todos los términos",
    glossaryEyebrow: "Glosario",
    contentsLabel: "Contenidos del glosario",
  },
};
